name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag my-image-name:$(date +%s) .
    - name: Run the docker image
      run: docker run -it  my-image-name:$(date +%s)
    - name: Publishiing docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
          name: safwanseban/go-github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
